from app.llm.base_llm import BaseLLM

print(BaseLLM)

class MockLLM(BaseLLM):
    """
    Mock implementation of the BaseLLM contract.

    Purpose:
        Simulate an LLM without calling an external provider.

    This implementation is useful for:
        - Application development
        - Testing
        - Debugging
        - Learning the application architecture
    """

    def generate_text(self, prompt: str) -> str:
        """
        Simulate text generation from an LLM.
        """

        return f"""
============================================================
Mock LLM Response
============================================================

Prompt Received:
------------------------------------------------------------
{prompt}

------------------------------------------------------------
Response:
This is a simulated response generated by MockLLM.

The application flow is working correctly.
"""